services:
  image-processing-api:
    build: .
    container_name: image-processing-api
    volumes:
      - ./app:/app
    ports:
      - "8078:8000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
